# Below is an example server configuration. You can specify a host, port,
# nickname, real name and channel for the bot to join. Please note that the
# channel is not prefixed with a hash.
#
#   server:
#       host: irc.example.com
#       port: 6667
#       nick: dudley
#       realname: Mr Dudley
#       channel: dnd
